//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestDbFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class Drone
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int IdLoadArea { get; set; }
        public int IdDeliveryArea { get; set; }
        public Nullable<int> IdPackage { get; set; }
        public Nullable<int> Distance { get; set; }
        public Nullable<int> MaxWeight { get; set; }
        public string Location { get; set; }
    
        public virtual DeliveryArea DeliveryArea { get; set; }
        public virtual LoadArea LoadArea { get; set; }
        public virtual Package Package { get; set; }
    }
}
